### ISSUE TITLE
composer_diff_exit_code value is always 0

### ISSUE THREAD

**Issue by weitzman** [IonBazan/composer-diff-action#7]
I just started using this action but it never posts a comment, even when there is output in the diff (because the exit code is 0). I think the issue is that the README is newer than the most recent release so the code that runs in the action doesn't match the posted docs. The needed PR is https://github.com/IonBazan/composer-diff-action/pull/5

**Comment by weitzman** [comment]
Hmm, I made a run with the master branch of this action and I still can't get a non-zero exit code https://github.com/massgov/openmass/runs/5887414952?check_suite_focus=true

**Comment by weitzman** [comment]
Here is a run with step debugging enabled. I think this suggests that the saved exit code is null https://github.com/massgov/openmass/runs/5887414952?check_suite_focus=true

**Comment by IonBazan** [comment]
@weitzman did you try running it with `strict: true`? If I recall correctly, the action will only report the exit code when this parameter is set.

**Comment by weitzman** [comment]
This has been fixed in master branch.
